---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content
  label: Homepage2
  match: "**/*"
- type: directory
  path: content
  label: Homepage
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - home-template
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
